import { lowSettings, startGame, sim } from './common.mjs';
export default async (page, shot) => {
  await lowSettings(page);
  await startGame(page);
  const step = () => page.evaluate(() => window.game.state.data.quest.step + ' ' + window.game.quest.title(window.game));
  const log = async (label) => console.log(label.padEnd(28), await step());
  await log('start');
  await page.evaluate(() => { const g = window.game; g.player.placeAt(g.ship.pos.clone().add(g.player.up.clone().multiplyScalar(0)).add(new g.ship.pos.constructor(5, 0, 5)), g.player.planet); });
  await sim(page, 0.5); await log('walked to ship');
  await page.evaluate(() => { window.game.state.give('hydrex', 45); });
  await sim(page, 0.3); await log('mined hydrex');
  await page.evaluate(() => { const g = window.game; const { allRecipes } = { allRecipes: null }; });
  await page.evaluate(() => { window.game.ui.openExosuit('crafting'); });
  await page.click('[data-action="craft:r_launch|1"]');
  await page.click('[data-action="tab:ship"]');
  await page.click('[data-action="recharge:launch|launch_fuel"]');
  await page.evaluate(() => window.game.ui.closeAll());
  await sim(page, 0.3); await log('crafted + refuelled');
  await page.evaluate(() => { const g = window.game; g.boardShip(); g.ship.tryLaunch(g); });
  await sim(page, 4);
  await page.evaluate(() => { const g = window.game; const p = g.ship.nearPlanet; const up = g.ship.pos.clone().sub(p.position).normalize(); g.ship.pos.copy(p.position).addScaledVector(up, p.atmosphereRadius + 2000); });
  await sim(page, 1); await log('reached orbit');
  await page.evaluate(() => { const g = window.game; const planet = g.world.system.planets.find(p => p.desc.hasSignal); const poi = g.pois.generate(planet, g).find(p => p.isSignal); g.player.placeAt(planet.toUniverse(poi.local.clone().addScaledVector(poi.dir, 1)), planet); g.setMode('foot'); });
  await sim(page, 0.5);
  await page.evaluate(() => { const g = window.game; g.quest.onMonolith(g.pois.pois.find(p => p.isSignal), g); g.ui.closeAll(); });
  await sim(page, 0.3); await log('attuned monolith');
  await page.evaluate(() => { const g = window.game; g.boardShip(); const s = g.world.system.stations[0]; g.ship.landedPlanet = null; g.ship.pos.copy(s.toUniverse(s.bayEntrance)); g.ship.setMode('flying'); g.ship.beginDocking(s); });
  await sim(page, 8); await log('docked');
  await page.evaluate(() => { const g = window.game; g.state.give('alloy_plate', 2); g.state.give('circuit', 1); g.state.give('tech_fragment', 2); g.state.addCredits(5000); });
  await page.click('[data-action="tab:tech"]');
  await page.click('[data-action="install:ship_hyperdrive"]');
  await sim(page, 0.3); await log('installed hyperdrive');
  console.log('range', await page.evaluate(() => window.game.state.jumpRange));
  await page.evaluate(() => { const g = window.game; g.state.give('astrium', 50); g.state.give('alloy_plate', 1); });
  await page.evaluate(() => { const g = window.game; g.ui.closeAll(); });
  await page.evaluate(() => window.game.undock());
  await sim(page, 6);
  await page.evaluate(() => window.game.ui.openExosuit('crafting'));
  await page.click('[data-action="craft:r_warp|1"]');
  await page.evaluate(() => window.game.ui.closeAll());
  await sim(page, 0.3); await log('crafted warp cell');
  const t = await page.evaluate(() => { const g = window.game; const n = g.galaxy.neighbours(g.state.data.systemId, g.state.jumpRange); g.ship.pos.addScaledVector(g.ship.forward, 3000); return g.jump(n[0].id); });
  console.log('jump started', t);
  await sim(page, 3); await page.waitForTimeout(3000); await sim(page, 6);
  await log('arrived');
  await shot('q_end');
};
